// TODO: look into loading this from the filesystem.
// Maybe https://github.com/pyros2097/rust-embed, if it works with wasm.

// Key:
// H: Household
// R: Road
// S: Store
pub(crate) static MAP_ASCII_STR: &str = "\
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
.R..R...R.....R.....R.....R......R.....R.....R.....R...R..R.
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
....R...R.....R.....R.....R......R.....R.....R.....R...R....
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
HHHRR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RRHHH
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
....R..................................................R....
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
HHHRRRHHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHHRRRHHH
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
HHHRRRHHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHHRRRHHH
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
HHHRRRHHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHHRRRHHH
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
HHHRRRHHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHHRRRHHH
HHH.R.HHH.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.HHH.R.HHH
....R.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....R....
....R........................RR........................R....
HHH.R..HHH...HHH...HHH.......RR.......HHH...HHH...HHH..R.HHH
HHHRR..HHH...HHH...HHH.......RR.......HHH...HHH...HHH..RRHHH
HHH.R..HHH...HHH...HHH.......RR.......HHH...HHH...HHH..R.HHH
....R...R.....R.....R........RR........R.....R.....R...R....
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
.R..R...R.....R.....R.....R......R.....R.....R.....R...R..R.
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
HHH.R..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..R.HHH
";
