// TODO: look into loading this from the filesystem.
// Maybe https://github.com/pyros2097/rust-embed, if it works with wasm.

// Key:
// H: Household
// R: Road
// S: Store
pub(crate) static MAP_ASCII_STR: &str = "\
....R..................................................R....
.HHHR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RHHH.
.HHHR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RHHH.
.HHHR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RHHH.
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
.HHHR.....HHH...HHH...HHH...HHHH...HHH...HHH...HHH.....RHHH.
.HHHR.....HHH...HHH...HHH...HHHH...HHH...HHH...HHH.....RHHH.
.HHHR.....HHH...HHH...HHH...HHHH...HHH...HHH...HHH.....RHHH.
....RHHH............................................HHHR....
....RHHH............................................HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
.HHHR..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........RHHH.
....RHHH.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......HHHR....
....RHHH.....................RR.....................HHHR....
....RHHH.....................RR.....................HHHR....
.HHHR.....HHH...HHH...HHH....RR....HHH...HHH...HHH.....RHHH.
.HHHR.....HHH...HHH...HHH....RR....HHH...HHH...HHH.....RHHH.
.HHHR.....HHH...HHH...HHH....RR....HHH...HHH...HHH.....RHHH.
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
.HHHR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RHHH.
.HHHR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RHHH.
.HHHR..HHH...HHH...HHH...HHH....HHH...HHH...HHH...HHH..RHHH.
....R..................................................R....
";
